### ISSUE TITLE
使用迅雷下载时提示找不到 get_token.js

### ISSUE THREAD

**Issue by YangTianz** [opennaslab/kubespider#222]
## Ask your question here:
```
2023-06-20 22:59:42,941-ERROR: Exception on /api/v1/download [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/kubespider/core/webhook_server.py", line 22, in decorated
    return func(*args, **kwargs)
  File "/app/kubespider/core/webhook_server.py", line 92, in download_handler
    err = download_trigger.kubespider_downloader.download_file(source, path, link_type)
  File "/app/kubespider/core/download_trigger.py", line 88, in download_file
    return self.handle_magnet_download(url, path, downloader_list, extra_param)
  File "/app/kubespider/core/download_trigger.py", line 129, in handle_magnet_download
    provider.load_config()
  File "/app/kubespider/download_provider/xunlei_download_provider/provider.py", line 73, in load_config
    with open(token_js_path, 'r', encoding='utf-8') as js_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/dependencies/xunlei_download_provider/get_token.js'
```
感觉是创建 container 的时候没有映射对路径？ 我是把 `get_token.js` 复制到了映射的目录里，然后改了一下配置就可以下载了

**Comment by qingchoulove** [comment]
感谢报告bug，kubespider在处理配置文件时，没有copy `get_token.js`到对应目录下。
大佬是否有兴趣贡献一个PR来修复这个问题呢？

**Comment by richardli1598** [comment]
相关代码在这里  https://github.com/opennaslab/kubespider/blob/d3d20147cd2f9a2d25ca612738809c4229f9331d/kubespider/core/config_handler.py#L148

**Comment by qingchoulove** [comment]
> 相关代码在这里
> 
> https://github.com/opennaslab/kubespider/blob/d3d20147cd2f9a2d25ca612738809c4229f9331d/kubespider/core/config_handler.py#L148

`download_provider.yaml`默认配置文件中 token_js_path 也需要调整
