### ISSUE TITLE
调试环境读取配置文件失败

### ISSUE THREAD

**Issue by ljtnono** [opennaslab/kubespider#224]
```txt

/Users/lingjiatong/code/kubespider/venv/bin/python3.10 /Users/lingjiatong/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/231.9011.38/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 49590 --file /Users/lingjiatong/code/kubespider/kubespider/app.py 
Connected to pydev debugger (build 231.9011.38)
2023-06-21 14:44:10,385-INFO: Config files(source_provider.yaml,download_provider.yaml,pt_provider.yaml,kubespider.yaml) miss, try to init them
Traceback (most recent call last):
  File "/Users/lingjiatong/code/kubespider/kubespider/core/config_handler.py", line 158, in prepare_config
    shutil.copy(template_cfg, target_cfg)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lingjiatong/.config_template/source_provider.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lingjiatong/code/kubespider/kubespider/core/config_handler.py", line 160, in prepare_config
    raise Exception(str('failed to copy %s to %s:%s', template_cfg, target_cfg)) from err
TypeError: decoding str is not supported

```

```python

for cfg in miss_cfg:
        template_cfg = values.CFG_TEMPLATE_PATH + cfg
        target_cfg = values.CFG_BASE_PATH + cfg
        try:
            shutil.copy(template_cfg, target_cfg)
        except Exception as err:
            raise Exception(str('failed to copy %s to %s:%s', template_cfg, target_cfg)) from err

```

应该是这里shutil.copy报的路径不存在问题

**Comment by qingchoulove** [comment]
Hello，非常感谢报告。这个问题是我们暂时没有对本地执行进行适配，需要手动复制配置到`${HOME}/.config/` 目录下。

**Comment by ljtnono** [comment]
> Hello，非常感谢报告。这个问题是我们暂时没有对本地执行进行适配，需要手动复制配置到`${HOME}/.config/` 目录下。

是否能够添加一个环境变量判断是开发环境还是docker容器环境

**Comment by qingchoulove** [comment]
嗯嗯 会加入到后续迭代规划中。如果大佬有兴趣也非常感谢提交PR。

**Comment by ljtnono** [comment]
> 嗯嗯 会加入到后续迭代规划中。如果大佬有兴趣也非常感谢提交PR。

提交一个PR

**Comment by ljtnono** [comment]
> 嗯嗯 会加入到后续迭代规划中。如果大佬有兴趣也非常感谢提交PR。

提交了一个PR
