### ISSUE TITLE
magnet download broken

### ISSUE THREAD

**Issue by lyq1996** [opennaslab/kubespider#357]
## Describe the bug
After updated the docker version of kubespider to the latest, I found that magnet downloader was broken.

Test website: 
https://archlinux.org/download/
![截屏2023-11-09 11 37 12](https://github.com/opennaslab/kubespider/assets/20365480/6f56126a-b808-4e0c-8bd9-2be9d1f03abf)

Error Log:
```
2023-11-09 11:11:40,382-INFO: Get webhook trigger:magnet:?xt=urn:btih:4d3e0fca47aac76ac05254c695c05f6adff3651e&dn=archlinux-2023.11.01-x86_64.iso
2023-11-09 11:11:40,382-ERROR: Exception on /api/v1/download [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/webhook_server.py", line 22, in decorated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/webhook_server.py", line 82, in download_handler
    err = source_manager.source_provider_manager.download_with_source_provider(event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/source_manager.py", line 25, in download_with_source_provider
    providers = self.find_source_provider(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/source_manager.py", line 19, in find_source_provider
    if not provider.should_handle(event):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/source_provider/meijutt_source_provider/provider.py", line 63, in should_handle
    if "www.meijutt" in parse_url.hostname and 'content' in parse_url.path:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Maybe related to this commit:
https://github.com/opennaslab/kubespider/commit/f06399df9f192a06ac70e2b7d66ee8eae1f53982

## Describe the running environment
OS: DSM 7.2.1-69057 Update 1
Docker IMAGE: cesign/kubespider latest

## My configurations:

download_provider(Provider that not enabled was not listed):
```
---
aria2:
  type: aria2_download_provider
  enable: true
  download_base_path: "/downloads/"
  rpc_endpoint_host: http://192.168.10.4
  rpc_endpoint_port: 6800
  secret: xxxxxxxx
  priority: 2
qbittorrent:
  type: qbittorrent_download_provider
  enable: true
  download_base_path: "/downloads/"
  http_endpoint_host: http://192.168.10.4
  http_endpoint_port: 8082
  username: xxxxxxxx
  password: xxxxxxxx
  verify_webui_certificate: false
  priority: 1
  tags:
    - kubespider
```
source_provider.yaml, notification_provider.yaml, pt_provider.yaml are default, and have not been modified.

**Comment by qingchoulove** [comment]
Thank you very much for the report. I will confirm the issue as soon

**Comment by miRemid** [comment]
@lyq1996 Hi, we have updated the image, plz have a try. If you encounter any issues please provide feedback

**Comment by lyq1996** [comment]
magnet downloader is now working, thank you all!
