### ISSUE TITLE
磁力下载失败

### ISSUE THREAD

**Issue by klaxonz** [opennaslab/kubespider#489]
## Describe the bug
磁力下载失败
```shell
2024-03-26 18:59:42,888-INFO: Source Provider:btbtt12_disposable_source_provider enabled...
2024-03-26 18:59:42,893-INFO: Source Provider:meijutt_source_provider enabled...
2024-03-26 18:59:42,897-INFO: Source Provider:bilibili_source_provider enabled...
2024-03-26 18:59:42,901-INFO: Source Provider:youtube_source_provider enabled...
2024-03-26 18:59:42,935-INFO: Download Provider:aria2 enabled...
2024-03-26 18:59:42,956-INFO: Period Server producer start running...
2024-03-26 18:59:42,957-INFO: Period Server Queue handler start running...
2024-03-26 18:59:42,957-INFO: PT Server start running...
2024-03-26 18:59:42,957-INFO: Download trigger job start running...
2024-03-26 18:59:42,957-INFO: Notification Server Queue handler start running...
2024-03-26 18:59:42,958-INFO: Webhook Server start running...
2024-03-26 18:59:42,960-INFO: Serving on http://0.0.0.0:3080
2024-03-26 18:59:43,961-INFO: meijutt tv link is:
2024-03-26 19:00:12,215-INFO: Get webhook trigger:magnet:?xt=urn:btih:f25d49b336075a2013a97c2f76bebc89cf40da80&dn=ncis.hawaii.s03e02.1080p.web.h264-nhtfs%5BEZTVx.to%5D.mkv%5Beztvx.to%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce
2024-03-26 19:00:12,215-ERROR: Exception on /api/v1/download [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/webhook_server.py", line 22, in decorated
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/webhook_server.py", line 82, in download_handler
    err = source_manager.source_provider_manager.download_with_source_provider(event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/source_manager.py", line 25, in download_with_source_provider
    providers = self.find_source_provider(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/core/source_manager.py", line 19, in find_source_provider
    if not provider.should_handle(event):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/kubespider/source_provider/bilibili_source_provider/provider.py", line 56, in should_handle
    parse_url = urlparse(re.findall(r"https?://\S+", event.source)[0])
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

## Describe the running environment

Runing OS: docker部署
Kuberspider version：lastest

**Comment by qingchoulove** [comment]
@klaxonz 麻烦更新最镜像验证下呢？

**Comment by klaxonz** [comment]
棒，更新后正常
