### ISSUE TITLE
在win下的wsl2里面启动就报错了，加了用户组之后就少了groupmod: invalid group ID 'kubespider'这个错误，其他的看不懂是什么问题

### ISSUE THREAD

**Issue by WilliamHWM** [opennaslab/kubespider#525]
13:53:50 Process Process-1:
2024-06-16 13:53:50 Traceback (most recent call last):
2024-06-16 13:53:50   File "/app/kubespider/core/config_handler.py", line 153, in get_notification_provider
2024-06-16 13:53:50     return notification_provider_init_func[provider_type](
2024-06-16 13:53:50            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
2024-06-16 13:53:50 KeyError: 'slack_notification_provider'
2024-06-16 13:53:50 
2024-06-16 13:53:50 During handling of the above exception, another exception occurred:
2024-06-16 13:53:50 
2024-06-16 13:53:50 Traceback (most recent call last):
2024-06-16 13:53:50   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-06-16 13:53:50     self.run()
2024-06-16 13:53:50   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-06-16 13:53:50     self._target(*self._args, **self._kwargs)
2024-06-16 13:53:50   File "/app/kubespider/core/runner.py", line 23, in run
2024-06-16 13:53:50     kubespider_controller.config()
2024-06-16 13:53:50   File "/app/kubespider/core/kubespider_controller.py", line 34, in config
2024-06-16 13:53:50     self.notifications_providers = config_handler.init_notification_config()
2024-06-16 13:53:50                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 13:53:50   File "/app/kubespider/core/config_handler.py", line 189, in init_notification_config
2024-06-16 13:53:50     init_notification_providers.append(get_notification_provider(name, conf))
2024-06-16 13:53:50                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 13:53:50   File "/app/kubespider/core/config_handler.py", line 158, in get_notification_provider
2024-06-16 13:53:50     raise Exception(str('unknown notification provider type %s', provider_type)) from exc
2024-06-16 13:53:50                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 13:53:50 TypeError: decoding str is not supported
2024-06-16 14:00:24 groupmod: invalid group ID 'kubespider'
2024-06-16 14:00:24 usermod: no changes
2024-06-16 14:00:24 
2024-06-16 14:00:24  _          _                     _     _
2024-06-16 14:00:24 | | ___   _| |__   ___  ___ _ __ (_) __| | ___ _ __
2024-06-16 14:00:24 | |/ / | | | '_ \ / _ \/ __| '_ \| |/ _` |/ _ \ '__|
2024-06-16 14:00:24 |   <| |_| | |_) |  __/\__ \ |_) | | (_| |  __/ |
2024-06-16 14:00:24 |_|\_\\__,_|_.__/ \___||___/ .__/|_|\__,_|\___|_|
2024-06-16 14:00:24                            |_|                    
2024-06-16 14:00:24     
2024-06-16 14:00:24 KubeSpider - A global resource download orchestration system
2024-06-16 14:00:24 Build Tag: ${GITHUB_SHA}
2024-06-16 14:00:24 2024-06-16 14:00:24,806-INFO: File handler start running...
2024-06-16 14:00:24 Process Process-1:
2024-06-16 14:00:24 Traceback (most recent call last):
2024-06-16 14:00:24   File "/app/kubespider/core/config_handler.py", line 153, in get_notification_provider
2024-06-16 14:00:24     return notification_provider_init_func[provider_type](
2024-06-16 14:00:24            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
2024-06-16 14:00:24 KeyError: 'slack_notification_provider'
2024-06-16 14:00:24 
2024-06-16 14:00:24 During handling of the above exception, another exception occurred:
2024-06-16 14:00:24 
2024-06-16 14:00:24 Traceback (most recent call last):
2024-06-16 14:00:24   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-06-16 14:00:24     self.run()
2024-06-16 14:00:24   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-06-16 14:00:24     self._target(*self._args, **self._kwargs)
2024-06-16 14:00:24   File "/app/kubespider/core/runner.py", line 23, in run
2024-06-16 14:00:24     kubespider_controller.config()
2024-06-16 14:00:24   File "/app/kubespider/core/kubespider_controller.py", line 34, in config
2024-06-16 14:00:24     self.notifications_providers = config_handler.init_notification_config()
2024-06-16 14:00:24                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 14:00:24   File "/app/kubespider/core/config_handler.py", line 189, in init_notification_config
2024-06-16 14:00:24     init_notification_providers.append(get_notification_provider(name, conf))
2024-06-16 14:00:24                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 14:00:24   File "/app/kubespider/core/config_handler.py", line 158, in get_notification_provider
2024-06-16 14:00:24     raise Exception(str('unknown notification provider type %s', provider_type)) from exc
2024-06-16 14:00:24                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-16 14:00:24 TypeError: decoding str is not supported

**Comment by miRemid** [comment]
感谢反馈问题，请问启动方式是什么？是否是docker形式部署的？

**Comment by WilliamHWM** [comment]
github 上写的bash hack/spiderinstall.sh 。用的docker方式



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 无题 ***@***.***&gt;
发送时间: 2024年6月16日 22:28
收件人: opennaslab/kubespider ***@***.***&gt;
抄送: WilliamHWM ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [opennaslab/kubespider] 在win下的wsl2里面启动就报错了，加了用户组之后就少了groupmod: invalid group ID 'kubespider'这个错误，其他的看不懂是什么问题 (Issue #525)





 
感谢反馈问题，请问启动方式是什么？是否是docker形式部署的？

**Comment by miRemid** [comment]
本机wsl2没有复现成功
![image](https://github.com/opennaslab/kubespider/assets/35894052/ed4fad30-721f-404e-bbde-4475309a0ab8)
os:  win11 23H2 wsl2 ubuntu 22.04
请问你使用的哪种方式安装的docker？如果使用的是Windows版本的Docker Desktop提供后端支持，请卸载删除后直接在wsl2中安装docker，`curl https://get.docker.com | sh`

**Comment by WilliamHWM** [comment]
curl https://get.docker.com | sh 装的docker拉取不到镜像的所以才去用了Docker Desktop提供后端支持，curl https://www.google.com 是可以正常访问的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opennaslab/kubespider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月17日(星期一) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opennaslab/kubespider] 在win下的wsl2里面启动就报错了，加了用户组之后就少了groupmod: invalid group ID 'kubespider'这个错误，其他的看不懂是什么问题 (Issue #525)





 
本机wsl2没有复现成功
 image.png (view on web)
 os:  win11 23H2 wsl2 ubuntu 22.04
 请问你使用的哪种方式安装的docker？如果使用的是Windows版本的Docker Desktop提供后端支持，请卸载删除后直接在wsl2中安装docker，curl https://get.docker.com | sh

**Comment by miRemid** [comment]
请给Docker更换镜像源，这部分可以参考[Daocloud](https://github.com/DaoCloud/public-image-mirror)
