### ISSUE TITLE
磁力链接下载经常报错

### ISSUE THREAD

**Issue by zctmdc** [opennaslab/kubespider#539]
## 群晖 7.2 3622xs+ 迅雷
Template: Linux eh-dsm 4.4.302+ #69057 SMP Fri Jan 12 17:02:26 CST 2024 x86_64 GNU/Linux synology_broadwellnk_3622xs+
cesign/kubespider                 latest        a64c096a972d 
"cesign/kubespider@sha256:320cb11e39f6c169c32463600e003d18a915c4620a8a5493691013cf13f8e4f9" 

只开了个迅雷

```python

    def download_kubespider(link, path=''):
        response  = requests.post(get_kubespider_url('/api/v1/download'), json={
            'dataSource': link,
            'path': path
        },verify=False)
        return response.text
    kp_result_1 = download_kubespider('magnet:?xt=urn:btih:123154AEBE22EB9811FF501A7E1BE1824E0C8298','/Downloads/vdown')

```
返回结果
```log
kp_result: 
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

docker 日志见下方 
```log
kubespider-kubespider-1  | 2024-08-14 11:34:34,895-INFO: Get webhook trigger:magnet:?xt=urn:btih:6719163914EBE627E4B7813416095ED88C9EF894
kubespider-kubespider-1  | 2024-08-14 11:34:34,895-ERROR: Exception on /api/v1/download [POST]
kubespider-kubespider-1  | Traceback (most recent call last):
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
kubespider-kubespider-1  |     response = self.full_dispatch_request()
kubespider-kubespider-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
kubespider-kubespider-1  |     rv = self.handle_user_exception(e)
kubespider-kubespider-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
kubespider-kubespider-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
kubespider-kubespider-1  |                                                 ^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
kubespider-kubespider-1  |     rv = self.dispatch_request()
kubespider-kubespider-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
kubespider-kubespider-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/webhook_server.py", line 23, in decorated
kubespider-kubespider-1  |     return func(*args, **kwargs)
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/webhook_server.py", line 83, in download_handler
kubespider-kubespider-1  |     err = source_manager.source_provider_manager.download_with_source_provider(event)
kubespider-kubespider-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/source_manager.py", line 25, in download_with_source_provider
kubespider-kubespider-1  |     providers = self.find_source_provider(event)
kubespider-kubespider-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/source_manager.py", line 19, in find_source_provider
kubespider-kubespider-1  |     if not provider.should_handle(event):
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/source_provider/btbtt12_disposable_source_provider/provider.py", line 59, in should_handle
kubespider-kubespider-1  |     if parse_url.hostname.endswith('btbtt12.com') and 'attach-dialog-fid' in parse_url.path:
kubespider-kubespider-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  | AttributeError: 'NoneType' object has no attribute 'endswith'
kubespider-kubespider-1  | 2024-08-14 12:34:10,196-INFO: meijutt tv link is:
kubespider-kubespider-1  | 2024-08-14 13:15:54,492-INFO: Get webhook trigger:magnet:?xt=urn:btih:123154AEBE22EB9811FF501A7E1BE1824E0C8298
kubespider-kubespider-1  | 2024-08-14 13:15:54,492-ERROR: Exception on /api/v1/download [POST]
kubespider-kubespider-1  | Traceback (most recent call last):
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
kubespider-kubespider-1  |     response = self.full_dispatch_request()
kubespider-kubespider-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
kubespider-kubespider-1  |     rv = self.handle_user_exception(e)
kubespider-kubespider-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask_cors/extension.py", line 178, in wrapped_function
kubespider-kubespider-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
kubespider-kubespider-1  |                                                 ^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
kubespider-kubespider-1  |     rv = self.dispatch_request()
kubespider-kubespider-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
kubespider-kubespider-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/webhook_server.py", line 23, in decorated
kubespider-kubespider-1  |     return func(*args, **kwargs)
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/webhook_server.py", line 83, in download_handler
kubespider-kubespider-1  |     err = source_manager.source_provider_manager.download_with_source_provider(event)
kubespider-kubespider-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/source_manager.py", line 25, in download_with_source_provider
kubespider-kubespider-1  |     providers = self.find_source_provider(event)
kubespider-kubespider-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/core/source_manager.py", line 19, in find_source_provider
kubespider-kubespider-1  |     if not provider.should_handle(event):
kubespider-kubespider-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  |   File "/app/kubespider/source_provider/btbtt12_disposable_source_provider/provider.py", line 59, in should_handle
kubespider-kubespider-1  |     if parse_url.hostname.endswith('btbtt12.com') and 'attach-dialog-fid' in parse_url.path:
kubespider-kubespider-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
kubespider-kubespider-1  | AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by popstk** [comment]
最新是0.7.0，这个pr https://github.com/opennaslab/kubespider/pull/540 还没merge进去，不过似乎也没解决完全，看下review

**Comment by qingchoulove** [comment]
> 最新是0.7.0，这个pr #540 还没merge进去，不过似乎也没解决完全，看下review

请稍等我检查下代码，有进展会在issues下更新

**Comment by qingchoulove** [comment]
@popstk 可能并不是迅雷的问题，在遍历source_provider是否可用时，发生了预期外的问题，稍后会发出修正PR

**Comment by qingchoulove** [comment]
@popstk 辛苦稍后更新latest版本重试，有问题请reopen此issues

**Comment by heywalter** [comment]
Same Issue, I've already updated the docker images with the latest version, but when down load file from the Ubuntu website, got this error:
2024-10-24 21:35:51,271-INFO: Download general file with downloader(aria2)
2024-10-24 21:35:51,276-INFO: Start general file download:Ubuntu Server 24.10
2024-10-24 21:35:51,276-WARNING: Download general file error:Aria2 do not support:Ubuntu Server 24.10

**Comment by qingchoulove** [comment]
> Same Issue, I've already updated the docker images with the latest version, but when down load file from the Ubuntu website, got this error: 2024-10-24 21:35:51,271-INFO: Download general file with downloader(aria2) 2024-10-24 21:35:51,276-INFO: Start general file download:Ubuntu Server 24.10 2024-10-24 21:35:51,276-WARNING: Download general file error:Aria2 do not support:Ubuntu Server 24.10

Hi, it looks like the input is not the download url but the title, can you describe the procedure in detail?

**Comment by heywalter** [comment]
> > Same Issue, I've already updated the docker images with the latest version, but when down load file from the Ubuntu website, got this error: 2024-10-24 21:35:51,271-INFO: Download general file with downloader(aria2) 2024-10-24 21:35:51,276-INFO: Start general file download:Ubuntu Server 24.10 2024-10-24 21:35:51,276-WARNING: Download general file error:Aria2 do not support:Ubuntu Server 24.10
> 
> Hi, it looks like the input is not the download url but the title, can you describe the procedure in detail?

When I finished the settings following KubeSpider tutorial, installed the chrome plugin, then visit the https://ubuntu.com/download/alternative-downloads page, right-click the [Ubuntu Server 24.10](https://releases.ubuntu.com/24.10/ubuntu-24.10-live-server-amd64.iso.torrent), click send to KubeSpider, then got this error from docker logs.

**Comment by qingchoulove** [comment]
@heywalter  The priority for handling chrome-extension is to first send the selected text. If no text is selected, then send the linkUrl of the right-clicked element. If both are unavailable, send the URL of the tab.Please check if the selected text was sent with the right-click. 
If there are still, please open a new issue to track.
